language: node_js
node_js: node
deploy:
  app: tranquil-shore-25586
  api_key:
    secure: Fzyjd8QN3kN5VMfxwPsx1tiSC4tQfQqXqayOLjP065M1ZrPtlf5nG5I7MEL6HelSlKmpkk5z+ZAsgvirvSOKGyGZUSzqUVmEzR7UZ8q5LgwE+AOIp3IS+lbuzLC9ji9oF6jDNBLWlniINNU2BScUMifi/Uz+jVilmv8MWLtqyZcDU3Y25zFcvwnc9J7tetPerEd9PLGMjMHw6+/o0WX1IKT0dTFGmvvVjkUbcp44eDJqdLMSf3KDsP/85Tyj4FIdMWitws6+kmpTVQqy4ofWwYlYwzlEKedzCM1yWfZUXkJMW47CIFAvbD2ygPo779G5k4E7XICE/iPSU5xb0FaZ9R6LlYYB0qnmPIMNVCwj2pqSD2LzbqRjqY08km5UzwXLksC0Edm3b+0tc7afM9uIDajglrRVll0pjPZ1nsxeYE0SFwrFmwVTJPxNJcJaL1mmgweD5w0CmZF5BZOd5Flkp8d8xamdxylsBRdvFpuhvc9q/5NnypvALebBzXFIwQf9yMAkv8e9BMKiIZa1zE8F5QRLaxF2j7F1y2Qr9Nrhu9ztv2q5UKSGBfQJnmdLtJ06ZvHp2i+c4HHFYMuhBk8gnBtp/5T9DZftWKsffRcQS2B3VtoKPGDmwh5zjaoudxz5twv/KXaKIJwbj0qqraW2haV7w2fLpRQBjMBkjPdfx+k=
